### PR TITLE
updates to deail with Quora format changes, date within documents

### PR DESCRIPTION
**Pull request by opoudjis**
* Quora format in HTML has changed, impacts download javascript and converter; updated README
* Changed converter to replace "x ago" dates within answers to real dates
* Changed crawler to deal with URL paths of blog posts from Quora

### CODE REVIEW

**Comment by t3nsor** [comment]
Thanks, I'll take a look when I have time.
How does one use your thing with blog posts? How do you get the list of URLs?

**Comment by opoudjis** [comment]
Same as how you get the list for answers. Go to your content, then select posts, then run the same Javascript (which I've had to update).

I've got a second update, now that I've converted blog posts: Reinserting H1, which has been taken out, and adding in detection of blog titles.

**Comment by t3nsor** [comment]
Hi Nick,

Thanks for opening this PR. I don't think I can accept it though, because it makes a lot of different changes and you haven't clearly explained what all of those changes are. For example, it seems like you've decided to change the output format so that it includes the original question text and the timestamp, and you've added some code to deal with "CredibilityFacts" and I have no idea what that means.

I welcome *fixes* to the codebase that become necessary as Quora changes its format (for example your updated JS in the readme) but if you want me to make changes to the output format, each such change should go in a separate PR and be properly documented so we can discuss it on its own. I am open to such changes but I think they should be controllable by flags.

Thanks!

**Comment by t3nsor** [comment]
Similarly, support for crawling/converting blog posts is good, but should go in a separate PR :)

**Comment by opoudjis** [comment]
@t3nsor Good open source citizenship goes both ways. After two years, I have no motivation to go back and revisit this. And of course, after two years, the format has changed again enough that my changes and those by @dda are obsolete.

I'd suggest some unit tests like with Travis. But I won't be writing them.

**Pull request closed without merging**
